### ISSUE TITLE
Attribute Error after upgrade to 3.12 

### ISSUE THREAD

**Issue by animal6496** [ned14/automodinit#7]
Just upgraded my system and now running with Python 3.12. This module now gives errors like:
```
   import automodinit
  File "/usr/local/lib/python3.12/site-packages/automodinit/__init__.py", line 4, in <module>
    ami(__name__, __file__, globals())
  File "/usr/local/lib/python3.12/site-packages/automodinit/automodinit.py", line 48, in automodinit
    module=loader.find_module(fullmodulename2).load_module(fullmodulename2)
           ^^^^^^^^^^^^^^^^^^
AttributeError: 'FileFinder' object has no attribute 'find_module'
```
Any suggestions?

**Comment by clement-cunin** [comment]
Hello,

automodinit are not compatible with python 3.12.
You can find alternative way to load all your module in this page: 
https://stackoverflow.com/questions/1057431/how-to-load-all-modules-in-a-folder

For me, I just replace automodinit by:

```
import pkgutil
for imp, module, ispackage in pkgutil.walk_packages(__path__, __name__+'.'):
  __import__(module)
```
